# Generated by Django 4.2.14 on 2024-07-20 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0002_rename_number_of_guests_reservation_number_of_people_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='reservation_time',
            field=models.TimeField(default='00:00:00'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='reservation_date',
            field=models.DateField(),
        ),
    ]
