# Generated by Django 4.2.14 on 2024-07-19 19:52

from django.db import migrations
import django_summernote.fields


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuitem',
            name='description',
            field=django_summernote.fields.SummernoteTextField(),
        ),
    ]
