# Generated by Django 4.2.14 on 2024-07-21 16:20

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0003_alter_menuitem_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='image',
            field=cloudinary.models.CloudinaryField(default='placeholder', max_length=255, verbose_name='image'),
        ),
    ]
