# Generated by Django 4.2.14 on 2024-07-19 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('table', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='table',
            name='seats',
            field=models.IntegerField(default=6),
        ),
    ]
